<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Entity\Model\Base;

class BundleCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'bundle_name',
        'type' => 'bundle_type',
        'component' => 'bundle_component',
        'info' => 'bundle_info',
        'entitytypeName' => 'bundle_entitytype_name',
        'group' => 'bundle_group',
        'created' => 'bundle_created',
        'updated' => 'bundle_updated',
    ];
}