<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Entity\Model\Base;

class FieldCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'data' => 'field_data',
        'id' => 'field_id',
        'created' => 'field_created',
        'updated' => 'field_updated',
        'bundleName' => 'field_bundle_name',
        'fieldconfigName' => 'field_fieldconfig_name',
    ];
}