<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Entity\Model\Base;

class FieldConfigCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'fieldconfig_name',
        'type' => 'fieldconfig_type',
        'system' => 'fieldconfig_system',
        'settings' => 'fieldconfig_settings',
        'property' => 'fieldconfig_property',
        'schema' => 'fieldconfig_schema',
        'schemaType' => 'fieldconfig_schema_type',
        'entitytypeName' => 'fieldconfig_entitytype_name',
        'bundleType' => 'fieldconfig_bundle_type',
        'created' => 'fieldconfig_created',
        'updated' => 'fieldconfig_updated',
    ];
}