<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Voting\Model\Base;

class VoteCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'bundleName' => 'vote_bundle_name',
        'entityId' => 'vote_entity_id',
        'value' => 'vote_value',
        'fieldName' => 'vote_field_name',
        'name' => 'vote_name',
        'comment' => 'vote_comment',
        'referenceId' => 'vote_reference_id',
        'hash' => 'vote_hash',
        'level' => 'vote_level',
        'id' => 'vote_id',
        'created' => 'vote_created',
        'updated' => 'vote_updated',
        'userId' => 'vote_user_id',
    ];
}