<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Display\Model\Base;

class DisplayCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'display_name',
        'bundleName' => 'display_bundle_name',
        'type' => 'display_type',
        'data' => 'display_data',
        'id' => 'display_id',
        'created' => 'display_created',
        'updated' => 'display_updated',
    ];
}