<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Display\Model\Base;

class ElementCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'element_name',
        'weight' => 'element_weight',
        'data' => 'element_data',
        'parentId' => 'element_parent_id',
        'system' => 'element_system',
        'elementId' => 'element_element_id',
        'id' => 'element_id',
        'created' => 'element_created',
        'updated' => 'element_updated',
        'displayId' => 'element_display_id',
    ];
}