<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Payment\Model\Base;

class FeatureGroupCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'logs' => 'featuregroup_logs',
        'bundleName' => 'featuregroup_bundle_name',
        'orderId' => 'featuregroup_order_id',
        'id' => 'featuregroup_id',
        'created' => 'featuregroup_created',
        'updated' => 'featuregroup_updated',
    ];
}