<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Payment\Model\Base;

class FeatureCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'status' => 'feature_status',
        'featureName' => 'feature_feature_name',
        'metas' => 'feature_metas',
        'logs' => 'feature_logs',
        'id' => 'feature_id',
        'created' => 'feature_created',
        'updated' => 'feature_updated',
        'featuregroupId' => 'feature_featuregroup_id',
    ];
}