<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\Directory\Model\Base;

class DirectoryCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'directory_name',
        'type' => 'directory_type',
        'data' => 'directory_data',
        'created' => 'directory_created',
        'updated' => 'directory_updated',
    ];
}