<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\View\Model\Base;

class FilterCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'filter_name',
        'type' => 'filter_type',
        'data' => 'filter_data',
        'bundleName' => 'filter_bundle_name',
        'fieldId' => 'filter_field_id',
        'id' => 'filter_id',
        'created' => 'filter_created',
        'updated' => 'filter_updated',
    ];
}