<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\View\Model\Base;

class ViewCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'view_name',
        'mode' => 'view_mode',
        'data' => 'view_data',
        'bundleName' => 'view_bundle_name',
        'default' => 'view_default',
        'id' => 'view_id',
        'created' => 'view_created',
        'updated' => 'view_updated',
    ];
}