<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\System\Model\Base;

class ComponentCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'name' => 'component_name',
        'version' => 'component_version',
        'priority' => 'component_priority',
        'config' => 'component_config',
        'events' => 'component_events',
        'created' => 'component_created',
        'updated' => 'component_updated',
    ];
}