<?php
/* This file has been auto-generated. Do not edit this file directly. */
namespace SabaiApps\Directories\Component\System\Model\Base;

class RouteCriteria extends \SabaiApps\Framework\Model\AbstractEntityCriteria
{
    protected $_keys = [
        'path' => 'route_path',
        'method' => 'route_method',
        'format' => 'route_format',
        'controller' => 'route_controller',
        'controllerComponent' => 'route_controller_component',
        'forward' => 'route_forward',
        'component' => 'route_component',
        'type' => 'route_type',
        'accessCallback' => 'route_access_callback',
        'titleCallback' => 'route_title_callback',
        'callbackPath' => 'route_callback_path',
        'callbackComponent' => 'route_callback_component',
        'weight' => 'route_weight',
        'depth' => 'route_depth',
        'priority' => 'route_priority',
        'data' => 'route_data',
        'language' => 'route_language',
        'admin' => 'route_admin',
        'id' => 'route_id',
        'created' => 'route_created',
        'updated' => 'route_updated',
    ];
}